// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/frontend.proto

package frontend

import (
	fmt "fmt"
	proto "google.golang.org/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "go-micro.dev/v4/api"
	client "go-micro.dev/v4/client"
	server "go-micro.dev/v4/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for Frontend service

func NewFrontendEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for Frontend service

type FrontendService interface {
	Call(ctx context.Context, in *CallRequest, opts ...client.CallOption) (*CallResponse, error)
	ClientStream(ctx context.Context, opts ...client.CallOption) (Frontend_ClientStreamService, error)
	ServerStream(ctx context.Context, in *ServerStreamRequest, opts ...client.CallOption) (Frontend_ServerStreamService, error)
	BidiStream(ctx context.Context, opts ...client.CallOption) (Frontend_BidiStreamService, error)
}

type frontendService struct {
	c    client.Client
	name string
}

func NewFrontendService(name string, c client.Client) FrontendService {
	return &frontendService{
		c:    c,
		name: name,
	}
}

func (c *frontendService) Call(ctx context.Context, in *CallRequest, opts ...client.CallOption) (*CallResponse, error) {
	req := c.c.NewRequest(c.name, "Frontend.Call", in)
	out := new(CallResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *frontendService) ClientStream(ctx context.Context, opts ...client.CallOption) (Frontend_ClientStreamService, error) {
	req := c.c.NewRequest(c.name, "Frontend.ClientStream", &ClientStreamRequest{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	return &frontendServiceClientStream{stream}, nil
}

type Frontend_ClientStreamService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	CloseSend() error
	Close() error
	Send(*ClientStreamRequest) error
}

type frontendServiceClientStream struct {
	stream client.Stream
}

func (x *frontendServiceClientStream) CloseSend() error {
	return x.stream.CloseSend()
}

func (x *frontendServiceClientStream) Close() error {
	return x.stream.Close()
}

func (x *frontendServiceClientStream) Context() context.Context {
	return x.stream.Context()
}

func (x *frontendServiceClientStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *frontendServiceClientStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *frontendServiceClientStream) Send(m *ClientStreamRequest) error {
	return x.stream.Send(m)
}

func (c *frontendService) ServerStream(ctx context.Context, in *ServerStreamRequest, opts ...client.CallOption) (Frontend_ServerStreamService, error) {
	req := c.c.NewRequest(c.name, "Frontend.ServerStream", &ServerStreamRequest{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	if err := stream.Send(in); err != nil {
		return nil, err
	}
	return &frontendServiceServerStream{stream}, nil
}

type Frontend_ServerStreamService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	CloseSend() error
	Close() error
	Recv() (*ServerStreamResponse, error)
}

type frontendServiceServerStream struct {
	stream client.Stream
}

func (x *frontendServiceServerStream) CloseSend() error {
	return x.stream.CloseSend()
}

func (x *frontendServiceServerStream) Close() error {
	return x.stream.Close()
}

func (x *frontendServiceServerStream) Context() context.Context {
	return x.stream.Context()
}

func (x *frontendServiceServerStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *frontendServiceServerStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *frontendServiceServerStream) Recv() (*ServerStreamResponse, error) {
	m := new(ServerStreamResponse)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

func (c *frontendService) BidiStream(ctx context.Context, opts ...client.CallOption) (Frontend_BidiStreamService, error) {
	req := c.c.NewRequest(c.name, "Frontend.BidiStream", &BidiStreamRequest{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	return &frontendServiceBidiStream{stream}, nil
}

type Frontend_BidiStreamService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	CloseSend() error
	Close() error
	Send(*BidiStreamRequest) error
	Recv() (*BidiStreamResponse, error)
}

type frontendServiceBidiStream struct {
	stream client.Stream
}

func (x *frontendServiceBidiStream) CloseSend() error {
	return x.stream.CloseSend()
}

func (x *frontendServiceBidiStream) Close() error {
	return x.stream.Close()
}

func (x *frontendServiceBidiStream) Context() context.Context {
	return x.stream.Context()
}

func (x *frontendServiceBidiStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *frontendServiceBidiStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *frontendServiceBidiStream) Send(m *BidiStreamRequest) error {
	return x.stream.Send(m)
}

func (x *frontendServiceBidiStream) Recv() (*BidiStreamResponse, error) {
	m := new(BidiStreamResponse)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for Frontend service

type FrontendHandler interface {
	Call(context.Context, *CallRequest, *CallResponse) error
	ClientStream(context.Context, Frontend_ClientStreamStream) error
	ServerStream(context.Context, *ServerStreamRequest, Frontend_ServerStreamStream) error
	BidiStream(context.Context, Frontend_BidiStreamStream) error
}

func RegisterFrontendHandler(s server.Server, hdlr FrontendHandler, opts ...server.HandlerOption) error {
	type frontend interface {
		Call(ctx context.Context, in *CallRequest, out *CallResponse) error
		ClientStream(ctx context.Context, stream server.Stream) error
		ServerStream(ctx context.Context, stream server.Stream) error
		BidiStream(ctx context.Context, stream server.Stream) error
	}
	type Frontend struct {
		frontend
	}
	h := &frontendHandler{hdlr}
	return s.Handle(s.NewHandler(&Frontend{h}, opts...))
}

type frontendHandler struct {
	FrontendHandler
}

func (h *frontendHandler) Call(ctx context.Context, in *CallRequest, out *CallResponse) error {
	return h.FrontendHandler.Call(ctx, in, out)
}

func (h *frontendHandler) ClientStream(ctx context.Context, stream server.Stream) error {
	return h.FrontendHandler.ClientStream(ctx, &frontendClientStreamStream{stream})
}

type Frontend_ClientStreamStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Recv() (*ClientStreamRequest, error)
}

type frontendClientStreamStream struct {
	stream server.Stream
}

func (x *frontendClientStreamStream) Close() error {
	return x.stream.Close()
}

func (x *frontendClientStreamStream) Context() context.Context {
	return x.stream.Context()
}

func (x *frontendClientStreamStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *frontendClientStreamStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *frontendClientStreamStream) Recv() (*ClientStreamRequest, error) {
	m := new(ClientStreamRequest)
	if err := x.stream.Recv(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (h *frontendHandler) ServerStream(ctx context.Context, stream server.Stream) error {
	m := new(ServerStreamRequest)
	if err := stream.Recv(m); err != nil {
		return err
	}
	return h.FrontendHandler.ServerStream(ctx, m, &frontendServerStreamStream{stream})
}

type Frontend_ServerStreamStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*ServerStreamResponse) error
}

type frontendServerStreamStream struct {
	stream server.Stream
}

func (x *frontendServerStreamStream) Close() error {
	return x.stream.Close()
}

func (x *frontendServerStreamStream) Context() context.Context {
	return x.stream.Context()
}

func (x *frontendServerStreamStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *frontendServerStreamStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *frontendServerStreamStream) Send(m *ServerStreamResponse) error {
	return x.stream.Send(m)
}

func (h *frontendHandler) BidiStream(ctx context.Context, stream server.Stream) error {
	return h.FrontendHandler.BidiStream(ctx, &frontendBidiStreamStream{stream})
}

type Frontend_BidiStreamStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*BidiStreamResponse) error
	Recv() (*BidiStreamRequest, error)
}

type frontendBidiStreamStream struct {
	stream server.Stream
}

func (x *frontendBidiStreamStream) Close() error {
	return x.stream.Close()
}

func (x *frontendBidiStreamStream) Context() context.Context {
	return x.stream.Context()
}

func (x *frontendBidiStreamStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *frontendBidiStreamStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *frontendBidiStreamStream) Send(m *BidiStreamResponse) error {
	return x.stream.Send(m)
}

func (x *frontendBidiStreamStream) Recv() (*BidiStreamRequest, error) {
	m := new(BidiStreamRequest)
	if err := x.stream.Recv(m); err != nil {
		return nil, err
	}
	return m, nil
}
